### ISSUE TITLE
VSCodium

### ISSUE THREAD

**Issue by probonopd** [zilti/code-oss.AppImage#1]
Hi @zilti how is this different from [VSCodium](https://github.com/VSCodium/vscodium/releases)?

**Comment by zilti** [comment]
Hm, I guess it is the same in a smaller package... I didn't know they offer an AppImage, since it isn't even mentioned on their main page

**Comment by zilti** [comment]
Oh also, my AppImage comes with embedded update info... Seems like the AppImage really is a barely-touched afterthought at VSCodium

**Comment by probonopd** [comment]
Just wondering whether it would make sense to contribute your improvements to VSCodium rather than have yet-another app variant? Your call.

**Comment by machitgarha** [comment]
@zilti Nowadays VSCodium support zsync AppImage update, as I tested.

**Comment by probonopd** [comment]
Let's use VSCodium then.
